# Autostart Section.

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = waybar &

# Cursor
exec-once = hyprctl setcursor $CursorTheme $cursorSize

# Brightness
exec-once = pkill wl-gammactl; wl-gammactl -c 0.85 -g 0.78 &

# Wallpaper
exec-once = awww-daemon &

# hyprpolkitagent
exec-once = systemctl --user start hyprpolkitagent

# Hotreload gtk theme.
exec = gsettings set org.gnome.desktop.interface gtk-theme "Adapta-Eta"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps

