[config.wallpaper]
command = "awww img --transition-type center {{ image }}"
set = true

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'
